version: '3.8'

services:
  database:
    image: postgres:14-alpine
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: performancekids
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - brinquedos-net

  app:
    build: .
    container_name: performance-kids
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/performancekids
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - brinquedos-net

networks:
  brinquedos-net:
    driver: bridge

volumes:
  pgdata: